### ISSUE TITLE
http://www.hivemq.com/demos/websocket-client/   dont work?

### ISSUE THREAD

**Issue by iot-lorawan** [hivemq/hivemq-mqtt-web-client#19]
Hi,
   the websocket client demo sample seem dont work, is it can work,or it have stop work and support.

http://www.hivemq.com/demos/websocket-client/

![图片](https://user-images.githubusercontent.com/30143031/100050843-4d5d7380-2e55-11eb-87f7-9bbc0840ef4e.png)

**Comment by schaebo** [comment]
@iot-lorawan: Thanks for contacting us. 
The demo works fine for me.
Can you elaborate what exactly doesn't work for you ? 
Maybe there is an error in your browser javascript console that you can share.

**Comment by iot-lorawan** [comment]
Hi,
   Thanks you for your quick respone, when click connect,the connectindcation is  always red,
my browser is
![图片](https://user-images.githubusercontent.com/30143031/100167547-46d50780-2efa-11eb-89ea-018973086a6f.png)

**Comment by fraschbi** [comment]
Hi @iot-lorawan,

The HiveMQ Websocket Demo works on Firefox.
Do you see any Javascript errors, [when inspecting the page](https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Open_the_Inspector)?

Regards,
Florian

**Comment by iot-lorawan** [comment]
Hi,
   the firefox debug console indicate error as below,
![图片](https://user-images.githubusercontent.com/30143031/100294912-2f158600-2fc3-11eb-98f7-ac015a190e54.png)

**Comment by FansinZhao** [comment]
I find the errors，the reason it cannot work is that some js scripts are not downloaded normally.Mabe you can modify some cdn js scripts like me,it will work again.

You will need refer my fork repo:
https://github.com/FansinZhao/hivemq-mqtt-web-client
or just use it,because i have make it into a docker image ,and pushed to docker hub.

Docker
`docker run -itd --rm -p 80:80 fansin/hivemq-mqtt-web-client`
then visit address `http://localhost/`, then, enjoy it.

**Comment by iot-lorawan** [comment]
Hi，
  Thanks.
